config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  # Resources
  resources :ledger_categories
  resources :financial_accounts
  resources :audits, only: %i[show index]
  resources :session_ratings
  resources :assignment_queues
  resources :courses
  resources :rating_reasons
  resources :series
  resources :class_locations
  resources :session_ratings, only: %i[show]
  resources :enrollments, only: %i[index]

  resources :general_ledgers do
    member do
      put :link
    end
  end

  resources :training_sessions do
    resources :enrollments, only: %i[create update destroy]

    get 'general_ledgers/link' => 'general_ledgers#show_link'
  end

  resources :training_requests do
    resources :training_request_polls

    get 'general_ledgers/link' => 'general_ledgers#show_link'

    post 'update_vote/:id' => 'training_request_polls#update_vote', as: 'vote'
    member do
      post 'add_requester'
      post 'update_requester_status/:requester_id', to: 'training_requests#update_requester_status', as: 'requester_status'
      delete 'destroy_requester/:requester_id' =>  'training_requests#destroy_requester'
    end
  end

  # Custom paths
  get 'enrollment_users', to: 'training_sessions#enrollment_users'
  get 'users/settings', to: 'users#edit_settings'
  get 'users/edit_password', to: 'users#edit_password'
  patch 'users/update_settings', to: 'users#update_settings', as: 'user_update_settings'

  get 'audit/users_list' => 'audits#users'
  get 'audit/options/:type' => 'audits#options', as: 'audit_options'
  get 'home/index'

  post 'assignment_round' => 'assignment_queues#assignment_round'

  #Grading paths
  post 'grading/grade_my_code', to: 'grading#grade_my_code', as: 'grade_my_code'

  # Users
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'sessions'
  }

  scope '/admin' do
    resources :users do
      collection do
        get 'available_admins' => 'users#available_training_admins', as: 'training_admins'
      end
    end
  end

  # Root
  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/class_location.rb
class ClassLocation < ApplicationRecord
  audited
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :timezone, presence: true
end

app/controllers/class_locations_controller.rb
class ClassLocationsController < ApplicationController
  before_action :set_class_location, only: [:show, :edit, :update, :destroy]

  load_and_authorize_resource

  # GET /class_locations
  # GET /class_locations.json
  def index
    @class_locations = ClassLocation.order(:name).page params[:page]
  end

  # GET /class_locations/1
  # GET /class_locations/1.json
  def show
  end

  # GET /class_locations/new
  def new
    @class_location = ClassLocation.new
  end

  # GET /class_locations/1/edit
  def edit
  end

  # POST /class_locations
  # POST /class_locations.json
  def create
    @class_location = ClassLocation.new(class_location_params)

    respond_to do |format|
      if @class_location.save
        format.html { redirect_to @class_location, notice: 'Class location was successfully created.' }
        format.json { render :show, status: :created, location: @class_location }
      else
        format.html { render :new }
        format.json { render json: @class_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /class_locations/1
  # PATCH/PUT /class_locations/1.json
  def update
    respond_to do |format|
      if @class_location.update(class_location_params)
        format.html { redirect_to @class_location, notice: 'Class location was successfully updated.' }
        format.json { render :show, status: :ok, location: @class_location }
      else
        format.html { render :edit }
        format.json { render json: @class_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /class_locations/1
  # DELETE /class_locations/1.json
  def destroy
    @class_location.destroy
    respond_to do |format|
      format.html { redirect_to class_locations_url, notice: 'Class location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_class_location
      @class_location = ClassLocation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def class_location_params
      params.require(:class_location).permit(:name, :email, :timezone)
    end
end

app/views/class_locations/_form.html.erb
<div class="panel panel-default">
  <div class="panel-body">

    <%= form_for(@class_location, html: {class: "form-horizontal", role: "form"}) do |f| %>
        <% if @class_location.errors.any? %>
            <div class="alert alert-danger alert-dismissable" role="alert">
              <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
              <h4><%= pluralize(@class_location.errors.count, 'error') %> prohibited this class_location from being
                saved:</h4>

              <ul>
                <% @class_location.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>



        <%= f.text_field :name %>
        <%= f.text_field :email %>
        <%= f.text_field :timezone %>

      <div class="form-group">
        <div class="col-sm-10">
        <%= f.submit class: 'btn btn-primary' %>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/class_locations/edit.html.erb
<% title 'Editing Class location' %>

<div class="row">
  <div class="container-fluid">
    <div class="pull-right">
      <%= link_to class_locations_path, class: 'btn btn-default' do %>
        <span class="glyphicon glyphicon-list-alt"></span>
        Back
      <% end %>
      <%= link_to @class_location, class: 'btn btn-primary' do %>
        <span class="glyphicon glyphicon-info-sign"></span>
        Show
      <% end %>
    </div>
  </div>
</div>


<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <h5><strong><%= yield :title %></strong></h5>
      </div>
      <div class="card-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/class_locations/index.html.erb
<% title 'Class locations' %>

<div class="card">

  <div class="card-header">
    <h5><strong><%= yield(:title) %></strong></h5>
  </div>

  <div class="card-body">

    <div class="row">
      <div class="col-12">

        <div class="pull-right">
          <% if current_user.has_cached_role?(:admin) %>
              <%= link_to new_class_location_path, class: 'btn btn-primary' do %>
                  <span class="glyphicon glyphicon-plus"></span>
                  New Class location
              <% end %>
          <% end %>
        </div>
      </div>
    </div>

    <br/>

    <div class="table-responsive">
      <table class="table table-responsive-sm table-hover mb-0">
        <thead class="thead-light">
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Timezone</th>
          <th>Actions</th>

        </tr>
        </thead>

        <tbody>
        <%= content_tag_for(:tr, @class_locations) do |class_location| %>
            <td><%= link_to class_location.name, class_location %></td>
            <td><%= class_location.email %></td>
            <td><%= class_location.timezone %></td>
            <td>
              <% if !current_user.has_cached_role?(:admin) %>
                  <%= link_to class_location_path(class_location) %>
              <% else %>
                  <%= crud_links class_location %>
              <% end %></td>
        <% end %>
        </tbody>
      </table>
    </div>

    <%= paginate @class_locations %>
  </div>
</div>

app/views/class_locations/new.html.erb
<% title 'New Class location' %>

<div class="row">
  <div class="container-fluid">
    <div class="pull-right">
      <%= link_to class_locations_path, class: 'btn btn-default' do %>
        <span class="glyphicon glyphicon-list-alt"></span>
        Back
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <%=  yield(:title) %>
      </div>
      <div class="card-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/class_locations/show.html.erb
<% title 'Class location' %>

<div class="row">
  <div class="container-fluid">
    <div class="pull-right">
      <%= link_to class_locations_path, class: 'btn btn-default' do %>
        <span class="glyphicon glyphicon-list-alt"></span>
        Back
      <% end %>
      <%= link_to edit_class_location_path(@class_location), class: 'btn btn-primary' do %>
        <span class="glyphicon glyphicon-pencil"></span>
        Edit
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <h5>Name: <strong><%= @class_location.name %></strong></h5>
      </div>
      <div class="card-body">
        <dl class="dl-horizontal">

          <dt>Email:</dt>
          <dd><%= @class_location.email %></dd>

          <dt>Timezone:</dt>
          <dd><%= @class_location.timezone %></dd>

        </dl>
      </div>
    </div>
  </div>
</div>