config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  # Resources
  resources :ledger_categories
  resources :financial_accounts
  resources :audits, only: %i[show index]
  resources :session_ratings
  resources :assignment_queues
  resources :courses
  resources :rating_reasons
  resources :series
  resources :class_locations
  resources :session_ratings, only: %i[show]
  resources :enrollments, only: %i[index]

  resources :general_ledgers do
    member do
      put :link
    end
  end

  resources :training_sessions do
    resources :enrollments, only: %i[create update destroy]

    get 'general_ledgers/link' => 'general_ledgers#show_link'
  end

  resources :training_requests do
    resources :training_request_polls

    get 'general_ledgers/link' => 'general_ledgers#show_link'

    post 'update_vote/:id' => 'training_request_polls#update_vote', as: 'vote'
    member do
      post 'add_requester'
      post 'update_requester_status/:requester_id', to: 'training_requests#update_requester_status', as: 'requester_status'
      delete 'destroy_requester/:requester_id' =>  'training_requests#destroy_requester'
    end
  end

  # Custom paths
  get 'enrollment_users', to: 'training_sessions#enrollment_users'
  get 'users/settings', to: 'users#edit_settings'
  get 'users/edit_password', to: 'users#edit_password'
  patch 'users/update_settings', to: 'users#update_settings', as: 'user_update_settings'

  get 'audit/users_list' => 'audits#users'
  get 'audit/options/:type' => 'audits#options', as: 'audit_options'
  get 'home/index'

  post 'assignment_round' => 'assignment_queues#assignment_round'

  #Grading paths
  post 'grading/grade_my_code', to: 'grading#grade_my_code', as: 'grade_my_code'

  # Users
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'sessions'
  }

  scope '/admin' do
    resources :users do
      collection do
        get 'available_admins' => 'users#available_training_admins', as: 'training_admins'
      end
    end
  end

  # Root
  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true
require 'elasticsearch/model'

class User < ApplicationRecord
  rolify

  include Searchable
  audited
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  has_many :training_sessions, through: 'instructors'
  has_many :enrollments
  has_many :assignment_queues
  validates :first_name, :last_name, presence: true

  # Get the user from the oauth hash values
  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first
    if user.nil?
      user = User.create(email: data['email'],
                         password: Devise.friendly_token[0, 20],
                         first_name: data['first_name'],
                         last_name: data['last_name'],
                         image: data['image'])
    else
      #refresh data
      user.update(first_name: data['first_name'],
                  last_name: data['last_name'],
                  image: data['image'])
    end

    user
  end

  def full_name
    first_name && last_name ? first_name + ' ' + last_name : ''
  end

  def to_s
    "#{first_name} #{last_name}<#{email}>"
  end

  # Callbacks
  before_create do |u|
    u.add_role :user
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController

  include AdvancedSearchHelper

  load_and_authorize_resource except: %i[available_training_admins]

  before_action :set_user, only: %i[show edit update destroy]
  before_action :set_current_user, only: %i[edit_settings edit_password]

  # GET /users
  # GET /users.json
  def index
    @users = if params[:q].blank?
               User.order(:email).page params[:page]
             else
               elastic_search_results(User)
             end
  end

  # GET /users/1
  # GET /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  def edit_settings; end

  def edit_password; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.add_role(:user)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(update_user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_settings
    respond_to do |format|
      if current_user.update(update_user_params)
        format.html { redirect_to root_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: current_user }
      else
        update_user_params.has_key?(:password) ? format.html { render :edit_password } : format.html { render :edit_settings }
        format.json { render json: current_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /users/available_admins.json
  def available_training_admins
    respond_to do |format|
      # format.html { raise ActionController::RoutingError, 'Not Found' }
      format.json do
        set_training_admins
        render :index, status: :ok
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  def set_current_user
    @user = current_user
  end

  def set_training_admins
    @users = AssignmentQueue.queue.map(&:user)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.fetch(:user, {})
          .permit(:q, :email, :password, :password_confirmation, :first_name,
                  :last_name, :vegetarian, :notification, role_ids: [])
  end

  def q_params
    params.require(:q)
          .permit(:email, :first_name, :last_name,
                  created_at: %i[start_date end_date])
  end

  # Remove the password to not validate it if is blank
  def update_user_params
    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    add_not_related_roles
  end

  # Add the instructor and user roles that the user already have
  def add_not_related_roles
    current_params = user_params.clone

    if user_params.key? :role_ids
      current_params[:role_ids] += @user
                                   .roles
                                   .where(name: %w[instructor user])
                                   .map { |u| u.id.to_s }
    end

    current_params
  end

end

app/views/users/_form.html.erb
<div class="page-section">
  <div class="row">
    <div class="col-md-10 col-lg-12 col-md-offset-1 col-lg-offset-2">
      <div class="panel panel-default">
        <div class="panel-body">
          <%= form_for @user, html: {class: 'form-horizontal', role: 'form'} do |f| %>
              <% if @user.errors.any? %>
                  <div class="alert alert-danger alert-dismissable" role="alert">
                    <button type="button" class="close" data-dismiss="alert">
                      <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4><%= pluralize(@user.errors.count, 'error') %> prohibited this training_request from being
                      saved:</h4>

                    <ul>
                      <% @user.errors.full_messages.each do |msg| %>
                          <li><%= msg %></li>
                      <% end %>
                    </ul>
                  </div>
              <% end %>

              <%= f.text_field :first_name, placeholder: 'Your first name' %>
              <%= f.text_field :last_name %>
              <%= f.email_field :email, placeholder: 'Enter email' %>
              <%= f.check_box :vegetarian %>
              <%= f.check_box :notification %>
              <%= f.password_field :password %>
              <%= f.password_field :password_confirmation %>

            <div class="form-group">
                <%= f.label 'Roles', class: 'col-sm-12 control-label', for: 'user_role_ids'%>
                <div class="col-sm-12">
                  <%= collection_check_boxes(
                      :user,
                      :role_ids,
                      Role.where.not(name: %w(instructor user)),
                      :id,
                      :name,
                      {}
                  ) do |b|%>
                  <%= b.label {b.check_box + b.text.capitalize.sub('_',' ')} %>
                    </br>
                  <% end %>

                </div>
              </div>
              <%= f.submit class: 'btn btn-primary' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_search_widget.html.erb
<!-- This is the content of the widget -->
<div class="row">
  <div class="col-12">

    <div class="pull-left">
      <%= form_tag(users_path, method: :get, class: 'form-inline') do %>

        <div class="form-group row">
          <div class="col-md-12">
            <div class="input-group">
              <%= text_field_tag :q, nil, class: 'form-control' %>
              <span class="input-group-btn">
              <%= button_tag nil, name: nil, class: 'btn btn-primary' do %>
                <i class="fa fa-search"></i> Search
              <% end %>
                <button class="btn btn-primary dropdown-toggle dropdown-toggle-split search-launcher" type="button" id="advanced" data-toggle="collapse" data-target="#user-search" aria-expanded="false" aria-controls="user-search">
                <span class="caret"></span>
                </button>
            </span>
            </div>
          </div>
        </div>

      <% end %>

      <br/>

      <div class="card advance-search-widget" id="user-search" data-active="false">
        <div class="card-header">
          Advanced Search
        </div>

        <div class="card-body">
          <%= form_for(:q, action: users_path, method: 'get', builder: ActionView::Helpers::FormBuilder) do |f| %>

            <div class="form-group">
              <div class="input-group">
                <span class="input-group-text"><i class="fa fa-user"></i></span>
                <%= f.text_field :first_name, class: 'form-control', placeholder: 'First name' %>
              </div>
            </div>

            <div class="form-group">
              <div class="input-group">
                <span class="input-group-text"><i class="fa fa-user"></i></span>
                <%= f.text_field :last_name, class: 'form-control', placeholder: 'Last name' %>
              </div>
            </div>

            <div class="form-group">
              <div class="input-group">
                <span class="input-group-text"><i class="fa fa-envelope"></i></span>
                <%= f.text_field :email, class: 'form-control', placeholder: 'Email' %>
              </div>
            </div>

            <div class="row">

              <div class="form-group col-6">
                <label for="q_created_at[start_date]">Created At</label>
                <div class="input-group">
                  <span class="input-group-text"><i class="fa fa-calendar"></i></span>
                  <%= f.text_field 'created_at[start_date]', class: 'form-control datepicker', placeholder: 'Start Date' %>
                </div>
              </div>

              <div class="form-group col-6">
                <label for="q_created_at[end_date]">&nbsp;</label>
                <div class="input-group">
                  <span class="input-group-text"><i class="fa fa-calendar"></i></span>
                  <%= f.text_field 'created_at[end_date]', class: 'form-control datepicker', placeholder: 'End Date' %>
                </div>
              </div>
            </div>

            <div class="form-group form-actions text-right" style="margin: 0">
              <%= f.button 'Search', name: 'search_widget', class: 'btn btn-primary', type: :submit do %>
                <i class="fa fa-search"></i> Search
              <% end %>
            </div>

          <% end %>
        </div>
      </div>
    </div>

    <div class="pull-right">
      <%= link_to new_user_path, class: 'btn btn-primary' do %>
        <span class="fa fa-plus"></span>
        New User
      <% end %>
    </div>

  </div>
</div>

app/views/users/edit.html.erb
<% title 'Editing user' %>

<div class="row">
  <div class="container-fluid">
    <div class="pull-right">

      <%= link_to users_path, class: 'btn btn-default' do %>
          <span class="glyphicon glyphicon-list-alt"></span>
          Back
      <% end %>
      <%= link_to @user, class: 'btn btn-primary' do %>
          <span class="glyphicon glyphicon-info-sign"></span>
          Show
      <% end %>

    </div>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <%= yield(:title) %>
      </div>
      <div class="card-body">

        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit_password.html.erb
<% title 'Editing password' %>

<div class="row">
  <div class="container-fluid">
    <div class="pull-right">

      <%= link_to :back, class: 'btn btn-default' do %>
          <span class="glyphicon glyphicon-list-alt"></span>
          Back
      <% end %>

    </div>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <%= yield(:title) %>
      </div>
      <div class="card-body">

        <div class="page-section">
          <div class="row">
            <div class="col-md-10 col-lg-8 col-md-offset-1 col-lg-offset-2">
              <div class="panel panel-default">
                <div class="panel-body">
                  <%= form_for current_user, url: user_update_settings_path, html: {class: 'form-horizontal', role: 'form'} do |f| %>
                      <% if current_user.errors.any? %>
                          <div class="alert alert-danger alert-dismissable" role="alert">
                            <button type="button" class="close" data-dismiss="alert">
                              <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                            <h4><%= pluralize(current_user.errors.count, 'error') %> prohibited this training_request from being
                              saved:</h4>

                            <ul>
                              <% current_user.errors.full_messages.each do |msg| %>
                                  <li><%= msg %></li>
                              <% end %>
                            </ul>
                          </div>
                      <% end %>
                      <div class="form-group">
                          <strong>User:
                          <%= current_user.full_name %></strong>
                      </div>
                      <div class="form-group">
                          <%= f.label 'New password', for: 'user_password' %><br>
                          <%= password_field_tag 'user[password]', nil %>
                      </div>
                      <div class="form-group">
                          <%= f.label 'New password confirmation', for: 'user_password_confirmation' %><br>
                          <%= password_field_tag 'user[password_confirmation]', nil %>
                      </div>
                      <div class="form-group">
                          <%= f.submit class: 'btn btn-primary' %>
                      </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit_settings.html.erb
<% title "User settings for: #{current_user.full_name}" %>

<div class="row">
  <div class="container-fluid">
    <div class="pull-right">

      <%= link_to :back, class: 'btn btn-default' do %>
          <span class="glyphicon glyphicon-list-alt"></span>
          Back
      <% end %>

    </div>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <h5><strong><%= yield(:title) %></strong></h5>
      </div>
      <div class="card-body">

        <div class="page-section">
          <div class="row">
            <div class="col-md-10 col-lg-8 col-md-offset-1 col-lg-offset-2">
              <div class="panel panel-default">
                <div class="panel-body">
                  <%= form_for current_user, url: user_update_settings_path, html: {class: 'form-horizontal', role: 'form'} do |f| %>
                      <% if current_user.errors.any? %>
                          <div class="alert alert-danger alert-dismissable" role="alert">
                            <button type="button" class="close" data-dismiss="alert">
                              <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                            <h4><%= pluralize(current_user.errors.count, 'error') %> prohibited this training_request from being
                              saved:</h4>

                            <ul>
                              <% current_user.errors.full_messages.each do |msg| %>
                                  <li><%= msg %></li>
                              <% end %>
                            </ul>
                          </div>
                      <% end %>

                      <%= f.text_field :first_name, placeholder: 'Your first name' %>
                      <%= f.text_field :last_name %>
                      <%= f.check_box :vegetarian %>
                      <%= f.check_box :notification %>

                      <%= f.submit class: 'btn btn-primary' %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% title 'Listing users' %>

<div class="card">
  <div class="card-header">
    <h5><strong><%= yield(:title) %></strong></h5>
  </div>

  <div class="card-body">

    <%= render 'search_widget' %>
    </br>
    <!-- Table with the users -->
    <div class="table-responsive">
      <table class="table table-responsive-sm table-hover mb-0">
        <thead class="thead-light">
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Creation Date</th>
          <th>Edition Date</th>
          <th class="text-center">Roles</th>
          <th>Actions</th>
        </tr>
        </thead>
        <tbody id="responsive-table-body">
        <%= content_tag_for(:tr, @users) do |user| %>
          <td><%= link_to user.full_name, user %></td>
          <td><%= user.email %></td>
          <td>
            <div class="small text-muted text-left">
              <%= user.created_at.strftime("%B %d, %Y") if user.created_at %>
            </div>
          </td>
          <td>
            <div class="small text-muted text-left">
              <%= user.updated_at.strftime("%B %d, %Y") if user.updated_at %>
            </div>
          </td>
          <td>
            <ul class="small text-muted">
              <% user.roles.where.not(name: :instructor).map do |r| %>
                <li>
                  <%= r.name.capitalize.sub('_',' ') %>
                </li>
              <% end %>
            </ul>
          </td>
          <td>

          <%= crud_links(user) %>

          </td>
        <% end %>
        </tbody>
      </table>
    </div>
    <!-- // Progress table -->


    <%= paginate @users %>
  </div>
</div>

app/views/users/new.html.erb
<% title 'New user' %>
<div class="row">
  <div class="container-fluid">
    <div class="pull-right">

      <%= link_to users_path, class: 'btn btn-default' do %>
          <span></span>
          Back
      <% end %>

    </div>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <%= yield(:title) %>
      </div>
      <div class="card-body">

        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% title 'Show user' %>
<div class="row">
  <div class="container-fluid">
    <div class="pull-right">


      <% if current_user.has_cached_role? :admin %>
        <%= link_to users_path, class: 'btn btn-default' do %>
            <span class="glyphicon glyphicon-list-alt"></span>
            Back
        <% end %>
        <%= link_to edit_user_path(@user), class: 'btn btn-primary' do %>
            <span class="glyphicon glyphicon-pencil"></span>
            Edit
        <% end %>
      <% else %>
          <%= link_to :back, class: 'btn btn-default' do %>
              <span class="glyphicon glyphicon-list-alt"></span>
              Back
          <% end %>
      <% end %>
    </div>
  </div>
</div>


<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <%= yield(:title) %>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-9">
          <dl>
            <dd class="dl-horizontal">
            <dt>Name:</dt>
            <dd><%= @user.full_name %></dd>

            <dt>Email:</dt>
            <dd><%= @user.email %></dd>

            <dt>Vegetarian:</dt>
            <dd><%= @user.vegetarian ? "Yes" : "No" %></dd>

            <dt>Notifications:</dt>
            <dd><%= @user.notification ? "Enabled" : "Disabled" %></dd>

            </dl>
          </div>

          <div class="col-3">

            <div class="card">
              <div class="card-header">
                Roles
              </div>

              <div class="card-body">
                <%=
                  nil
                  @user.roles.each do |role|
                %>
                  <li><%= role[:name].capitalize.sub('_',' ') %></li>
                  <% end %>

              </div>

            </div>

          </div>

        </div>

      </div>
    </div>
  </div>
</div>