config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  # Resources
  resources :ledger_categories
  resources :financial_accounts
  resources :audits, only: %i[show index]
  resources :session_ratings
  resources :assignment_queues
  resources :courses
  resources :rating_reasons
  resources :series
  resources :class_locations
  resources :session_ratings, only: %i[show]
  resources :enrollments, only: %i[index]

  resources :general_ledgers do
    member do
      put :link
    end
  end

  resources :training_sessions do
    resources :enrollments, only: %i[create update destroy]

    get 'general_ledgers/link' => 'general_ledgers#show_link'
  end

  resources :training_requests do
    resources :training_request_polls

    get 'general_ledgers/link' => 'general_ledgers#show_link'

    post 'update_vote/:id' => 'training_request_polls#update_vote', as: 'vote'
    member do
      post 'add_requester'
      post 'update_requester_status/:requester_id', to: 'training_requests#update_requester_status', as: 'requester_status'
      delete 'destroy_requester/:requester_id' =>  'training_requests#destroy_requester'
    end
  end

  # Custom paths
  get 'enrollment_users', to: 'training_sessions#enrollment_users'
  get 'users/settings', to: 'users#edit_settings'
  get 'users/edit_password', to: 'users#edit_password'
  patch 'users/update_settings', to: 'users#update_settings', as: 'user_update_settings'

  get 'audit/users_list' => 'audits#users'
  get 'audit/options/:type' => 'audits#options', as: 'audit_options'
  get 'home/index'

  post 'assignment_round' => 'assignment_queues#assignment_round'

  #Grading paths
  post 'grading/grade_my_code', to: 'grading#grade_my_code', as: 'grade_my_code'

  # Users
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'sessions'
  }

  scope '/admin' do
    resources :users do
      collection do
        get 'available_admins' => 'users#available_training_admins', as: 'training_admins'
      end
    end
  end

  # Root
  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/assignment_queue.rb
class AssignmentQueue < ApplicationRecord

  resourcify
  audited

  include Searchable

  belongs_to :user
  belongs_to :training_request, required: false

  enum status: ASSIGNMENT_STATUS

  validates :status, presence: true, inclusion: {in: statuses.keys , message: 'The value: %{value} is not a valid status'}
  validates :assignment_order, presence: true, numericality: true

  scope :queue, lambda {
    where(status: 'ACTIVE')
      .order(:id, :assignment_order)
      .uniq(&:user_id)
  }

  # Generates a new assignment round for the
  # pending training requests
  def self.assignment_round
    AssignmentQueue.create(User.with_role(:training_admin).map
                               .with_index do |u, i|
                                 { assignment_order: (i + 1),
                                   status: 'ACTIVE',
                                   user_id: u.id }
                               end)
  end

  # Get the next value in the queue
  def self.next_in_queue
    queue.first
  end

end

app/controllers/assignment_queues_controller.rb
# frozen_string_literal: true

class AssignmentQueuesController < ApplicationController
  load_and_authorize_resource

  before_action :set_assignment_queue, only: %i[show edit update destroy]

  # GET /assignment_queues
  # GET /assignment_queues.json
  def index
    if params[:q].blank?
      @assignment_queues = AssignmentQueue.order(id: :desc).includes(:user, :training_request).page params[:page]
    else
      @assignment_queues = AssignmentQueue.search(params[:q]).page(params[:page]).records
    end
  end

  # GET /assignment_queues/1
  # GET /assignment_queues/1.json
  def show; end

  # GET /assignment_queues/new
  def new
    @assignment_queue = AssignmentQueue.new
  end

  # GET /assignment_queues/1/edit
  def edit; end

  # POST /assignment_queues
  # POST /assignment_queues.json
  def create
    @assignment_queue = AssignmentQueue.new(assignment_queue_params)

    respond_to do |format|
      if @assignment_queue.save
        format.html { redirect_to @assignment_queue, notice: 'Assignment queue was successfully created.' }
        format.json { render :show, status: :created, location: @assignment_queue }
      else
        format.html { render :new }
        format.json { render json: @assignment_queue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assignment_queues/1
  # PATCH/PUT /assignment_queues/1.json
  def update
    respond_to do |format|
      if @assignment_queue.update(assignment_queue_params)
        format.html { redirect_to @assignment_queue, notice: 'Assignment queue was successfully updated.' }
        format.json { render :show, status: :ok, location: @assignment_queue }
      else
        format.html { render :edit }
        format.json { render json: @assignment_queue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignment_queues/1
  # DELETE /assignment_queues/1.json
  def destroy
    @assignment_queue.destroy
    respond_to do |format|
      format.html { redirect_to assignment_queues_url, notice: 'Assignment queue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /assignment_round
  # POST /assignment_round.json
  def assignment_round
    AssignmentQueue.assignment_round

    respond_to do |format|
      format.html do
        flash[:notice] = 'New assignment round generated'
        redirect_to action: :index
      end
      format.json { redirect_to action: :index, status: :ok }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_assignment_queue
    @assignment_queue = AssignmentQueue.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def assignment_queue_params
    params.require(:assignment_queue).permit(:assignment_order, :status, :user_id, :training_request_id)
  end
end

app/views/assignment_queues/_assignment_queue_table.html.erb
<div class="table-responsive">
  <table class="table table-responsive-sm table-hover mb-0">
    <thead class="thead-light">
    <tr>
      <th>Assignment order</th>
      <th>Status</th>
      <th>User</th>
      <th>Training request</th>
      <th>Actions</th>

    </tr>
    </thead>

    <tbody>
    <%= content_tag_for(:tr, @assignment_queues) do |assignment_queue| %>
        <td><%= link_to assignment_queue.assignment_order, assignment_queue_path(assignment_queue) %></td>
        <td><%= assignment_queue.status.capitalize %></td>
        <td>
          <%= assignment_queue.user.first_name + ' ' + assignment_queue.user.last_name %>
          <div class="small text-muted">
            <%= assignment_queue.user.email %>
          </div>
        </td>
        <td>
          <% if assignment_queue.training_request %>
              <%= link_to training_request_path(assignment_queue.training_request) do %>
                  <%= assignment_queue.training_request.name %>
                  <div class="small text-muted">
                    # <%= assignment_queue.training_request.id %>
                  </div>
              <% end %>
          <% end %>
        </td>
        <td>
          <% if current_user.has_cached_role?(:admin) || current_user.has_cached_role?(:training_admin) %>
              <%= crud_links assignment_queue %>
          <% end %></td>

    <% end %>
    </tbody>
  </table>
</div>

<br/>

<%= paginate @assignment_queues %>

app/views/assignment_queues/_form.html.erb
<div class="panel panel-default">
  <div class="panel-body">

    <%= form_for(@assignment_queue, html: {class: "form-horizontal", role: "form"}) do |f| %>
        <% if @assignment_queue.errors.any? %>
            <div class="alert alert-danger alert-dismissable" role="alert">
              <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
              <h4><%= pluralize(@assignment_queue.errors.count, "error") %> prohibited this assignment_queue from being
                saved:</h4>

              <ul>
                <% @assignment_queue.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="form-group">
          <%= f.text_field :assignment_order %>
          <div class="form-group">
            <%= f.label 'Assignment Queue', class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
              <%= f.select :assignment_queue, :status, [['assigned','assigned'],['skipped','skipped'],['active','active']], selected: @assignment_queue.status %>
            </div>
          </div>
          <%= f.autocomplete :user %>
          <%= f.autocomplete :training_request %>

          <div class="form-group">
            <div class="col-sm-10">
              <%= f.submit class: 'btn btn-primary' %>
            </div>
          </div>
        </div>

    <% end %>
  </div>
</div>

app/views/assignment_queues/edit.html.erb
<% title 'Editing Assignment Queue' %>

<div class="row">
  <div class="container-fluid">
    <div class="pull-right">
      <%= link_to assignment_queues_path, class: 'btn btn-default' do %>
          <span class="glyphicon glyphicon-list-alt"></span>
          Back
      <% end %>
      <%= link_to @assignment_queue, class: 'btn btn-primary' do %>
          <span class="glyphicon glyphicon-info-sign"></span>
          Show
      <% end %>
    </div>
  </div>
</div>


<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        Assignment Queues
      </div>
      <div class="card-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/assignment_queues/index.html.erb
<% title 'Assignment Queues for Training Request' %>


<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <h5><strong><%= yield(:title) %></strong></h5>
      </div>
      <div class="card-body">

        <div class="row">
          <div class="col-12">
            <%= form_tag(assignment_queues_path, method: :get, class: 'form-inline pull-left') do %>

                <div class="form-group row">
                  <div class="col-md-12">
                    <div class="input-group">
                      <%= text_field_tag :q, params[:q], class: 'form-control' %>
                      <span class="input-group-btn">
                      <%= button_tag nil, assignment_order: nil, class: 'btn btn-primary' do %>
                        <i class="fa fa-search"></i> Search
                      <% end %>
                    </span>
                    </div>
                  </div>
                </div>

            <% end %>

            <div class="pull-right">
              <% if current_user.has_cached_role?(:admin) || current_user.has_cached_role?(:training_admin) %>
                  <%= link_to assignment_round_path, method: :post, class: 'btn btn-primary' do %>
                    <span class="fa fa-refresh"></span>
                    New Assignment Round
                  <% end %>

                  <%= link_to new_assignment_queue_path, class: 'btn btn-primary' do %>
                    <span class="fa fa-plus"></span>
                    New Assignment Queue
                  <% end %>
              <% end %>
            </div>
          </div>
        </div>
        <br>

        <%= render 'assignment_queues/assignment_queue_table' %>
      </div>
    </div>
  </div>
</div>

app/views/assignment_queues/new.html.erb
<% title 'New Assignment Queue' %>

<div class="row">
  <div class="container-fluid">
    <div class="pull-right">
      <%= link_to assignment_queues_path, class: 'btn btn-default' do %>
          <span class="glyphicon glyphicon-list-alt"></span>
          Back
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <%=  yield(:title) %>
      </div>
      <div class="card-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/assignment_queues/show.html.erb
<% title 'Assignment Queue' %>
<div class="row">
  <div class="container-fluid">
    <div class="pull-right">
      <%= link_to assignment_queues_path, class: 'btn btn-default' do %>
          <span class="glyphicon glyphicon-list-alt"></span>
          Back
      <% end %>
      <%= link_to edit_assignment_queue_path(@assignment_queue), class: 'btn btn-primary' do %>
          <span class="glyphicon glyphicon-pencil"></span>
          Edit
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <h4 class="text-headline">
          Assignment Queue
        </h4>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-md-8">
            <% if @assignment_queue.training_request.blank? %>
                <%= "Assignment Queue without Training Request:" %></h4>
            <% else %>
                <strong>
                  <%= "Training request: #{@assignment_queue.training_request.name.capitalize}" %></h4>
                  </strong>
            <% end %>
          </div>
          <div class="col-md-3 col-md-offset-1">
            <p class="text-caption">
              <strong>
                <i class="fa fa-chevron-circle-right fa-fw"></i> Assignment Order: <%= @assignment_queue.assignment_order %> <br>
                <i class="fa fa-user-circle fa-fw"></i> Lead User: <%= @assignment_queue.user %>
                <br/>
                <i class="fa fa-bookmark fa-fw"></i> Status: <%= @assignment_queue.status %>
              </strong>
            </p>
          </div>
        </div>

        <hr class="margin-none"/>


      </div>
    </div>
  </div>
</div>