config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  # Resources
  resources :ledger_categories
  resources :financial_accounts
  resources :audits, only: %i[show index]
  resources :session_ratings
  resources :assignment_queues
  resources :courses
  resources :rating_reasons
  resources :series
  resources :class_locations
  resources :session_ratings, only: %i[show]
  resources :enrollments, only: %i[index]

  resources :general_ledgers do
    member do
      put :link
    end
  end

  resources :training_sessions do
    resources :enrollments, only: %i[create update destroy]

    get 'general_ledgers/link' => 'general_ledgers#show_link'
  end

  resources :training_requests do
    resources :training_request_polls

    get 'general_ledgers/link' => 'general_ledgers#show_link'

    post 'update_vote/:id' => 'training_request_polls#update_vote', as: 'vote'
    member do
      post 'add_requester'
      post 'update_requester_status/:requester_id', to: 'training_requests#update_requester_status', as: 'requester_status'
      delete 'destroy_requester/:requester_id' =>  'training_requests#destroy_requester'
    end
  end

  # Custom paths
  get 'enrollment_users', to: 'training_sessions#enrollment_users'
  get 'users/settings', to: 'users#edit_settings'
  get 'users/edit_password', to: 'users#edit_password'
  patch 'users/update_settings', to: 'users#update_settings', as: 'user_update_settings'

  get 'audit/users_list' => 'audits#users'
  get 'audit/options/:type' => 'audits#options', as: 'audit_options'
  get 'home/index'

  post 'assignment_round' => 'assignment_queues#assignment_round'

  #Grading paths
  post 'grading/grade_my_code', to: 'grading#grade_my_code', as: 'grade_my_code'

  # Users
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'sessions'
  }

  scope '/admin' do
    resources :users do
      collection do
        get 'available_admins' => 'users#available_training_admins', as: 'training_admins'
      end
    end
  end

  # Root
  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/training_session.rb
require 'elasticsearch/model'


class TrainingSession < ApplicationRecord
  resourcify
  audited
  include Searchable

  enum session_type: {
    workshop: 'WORKSHOP',
    in_person_class: 'IN_PERSON_CLASS',
    online_class: 'ONLINE_CLASS'
  }

  belongs_to :course, optional: true
  belongs_to :class_location
  has_many :enrollments
  has_many :general_ledgers

  has_and_belongs_to_many :instructors, class_name: 'User', join_table: 'instructors'
  accepts_nested_attributes_for :instructors

  validates :title, presence: true
  validates :description, presence: true
  validates :min_group_size, presence: true
  validates :max_group_size, presence: true
  validates :start_date, presence: true
  validates :duration_in_minutes, presence: true, numericality: true
  validates :session_type, presence: true, inclusion: {in: session_types.keys, message: 'The value: %{value} is not a valid session type'}


  def instructors_attributes=(attributes)
    self.instructors = attributes.map { |user| User.find(user['id']) }
    super(attributes)
  end

  def full?
    enrollments.count >= max_group_size
  end

  def enrolled_user?(user)
    enrollments.any? { |e| e.user_id == user.id }
  end

  def enrolled_and_attended_user?(user)
    enrollments.any? { |e| e.user_id == user.id && e.attended }
  end

  def attendance
    enrollments.where(attended: true).count
  end

  # Callbacks
  after_save do

    # Clean the preview instructors list
    current_instructors = User.with_role(:instructor, self).preload(:roles)
    current_instructors.each do |i|
      i.remove_role(:instructor, self) if i.has_cached_role?(:instructor, self)
    end

    # Set the users in the instructors list as instructors of
    # the training session
    instructors.each { |u| u.add_role(:instructor, self) }
  end

  def total_planned
    total_type 'PLANNED'
  end

  def total_debit
    total_type 'DEBIT'
  end

  def total_credit
    total_type('CREDIT') * -1
  end

  def end_date
    start_date + duration_in_minutes.minutes
  end

  def summary
    "#{title}: #{description}"
  end

  def enrolled_and_instructors_ids
    enrollments.map(&:id).concat(instructors.ids)
  end

  def start_time
    begin
      "#{start_date.hour}:#{'%02d' % start_date.min}"
    rescue NoMethodError
      ""
    end
  end

  private

  def total_type type
    Money.new(general_ledgers.select { |gl| gl.transaction_type == type }
      .inject(0) { |sum, gl| sum + gl.amount } * 100)
  end
end

app/controllers/training_sessions_controller.rb
# frozen_string_literal: true
class TrainingSessionsController < ApplicationController
  load_and_authorize_resource

  include GoogleCalendar

  before_action :set_training_session, only: %i[show edit update destroy enrollment_users]

  # GET /training_sessions
  # GET /training_sessions.json
  def index
    if current_user.has_cached_role?(:workshops_admin) || current_user.has_cached_role?(:admin)
      if params[:q].blank?
        @training_sessions = TrainingSession.order(start_date: :desc).includes(:course, :class_location).page params[:page]
      else
        # TODO: we need to move this `import` call to an initializer or something similar
        # TrainingSession.import force: true
        @training_sessions = TrainingSession.search(params[:q]).page(params[:page]).records
      end
    else
      if params[:q].blank?
        @training_sessions = TrainingSession
                             .where(published: true)
                             .order(start_date: :desc)
                             .includes(:course, :class_location).page params[:page]
      else
        @training_sessions = TrainingSession.search(params[:q]).records.where(published: true).page(params[:page])
      end
    end
  end

  # GET /training_sessions/1
  # GET /training_sessions/1.json
  def show
    @user_enrollment = Enrollment.find_by(user: current_user,
                                          training_session: @training_session)

    # This variable is used on the General Ledger modal partial
    @general_ledger = GeneralLedger.new
    @session_rating = SessionRating
                      .find_or_initialize_by(user: current_user,
                                             enrollment: @user_enrollment)
  end

  # GET /enrollment_users
  def enrollment_users
    enrolled_users = @training_session.enrolled_and_instructors_ids

    @users = if params[:q].blank?
               User
             else
               User.search(params[:q]).records
             end.where.not(id: enrolled_users)
             .page params[:page]
  end

  # GET /training_sessions/new
  def new
    @training_session = TrainingSession.new
  end

  # GET /training_sessions/1/edit
  def edit; end

  # POST /training_sessions
  # POST /training_sessions.json
  def create
    @training_session = TrainingSession.new(training_session_params)
    respond_to do |format|
      if @training_session.valid?
        @training_session.google_calendar_event_id = create_event(
          start_date: @training_session.start_date,
          end_date: @training_session.end_date,
          summary: @training_session.summary )
        @training_session.google_calendar_id = ENV['CALENDAR_EMAIL']
        if @training_session.save
          format.html { redirect_to @training_session, notice: 'Training session was successfully created.' }
          format.json { render :show, status: :created, location: @training_session }
        else
          format.html { render :new }
          format.json { render json: @training_session.errors, status: :unprocessable_entity }
        end
      else
        format.html { render :new }
        format.json { render json: @training_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /training_sessions/1
  # PATCH/PUT /training_sessions/1.json
  def update
    respond_to do |format|
      if @training_session.update(training_session_params)
        format.html { redirect_to @training_session, notice: 'Training session was successfully updated.' }
        format.json { render :show, status: :ok, location: @training_session }
      else
        format.html { render :edit }
        format.json { render json: @training_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /training_sessions/1
  # DELETE /training_sessions/1.json
  def destroy
    @training_session.destroy
    respond_to do |format|
      format.html { redirect_to training_sessions_url, notice: 'Training session was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_training_session
    @training_session = TrainingSession
                        .includes(:general_ledgers, :instructors,
                                  :class_location)
                        .includes(general_ledgers:
                                      %i[financial_account ledger_category])
                        .includes(enrollments: [
                                    { session_rating: :user },
                                    :user
                                  ])
                        .find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def training_session_params
    params.require(:training_session)
          .permit(:q, :title, :description, :min_group_size, :max_group_size,
                  :start_date, :url, :duration_in_minutes, :compensation,
                  :compensation_delivered, :session_type, :course_id,
                  :published, :class_location_id, instructor_ids: [], instructors_attributes: [:id])
  end
end

app/helpers/training_session_helper.rb
# frozen_string_literal: true

# Helper actions for the Training Sessions
module TrainingSessionHelper

  # Generates an HTML 5 starts element to rate a training instructor
  def session_rate(rate, options = {})
    capture do
      (1..5).each do |i|
        if options.key?(:clickable) && options[:clickable]
          concat link_to_rate(i, i <= rate)
        else
          concat content_tag(:i, nil, id: "rate_#{i}",
                             class: i <= rate ? 'fa fa-star' : 'fa fa-star-o')
        end
      end
    end
  end

  # Generates a link with a start inside to rate a training instructor
  def link_to_rate(rate, filled)
    link_to(nil,
            data: { toggle: 'modal', target: '#ratingModal', rating: rate }, id: "rate_#{rate}") do
      content_tag(:i, nil, class: filled ? 'fa fa-star' : 'fa fa-star-o')
    end
  end
end

app/views/training_sessions/_enrollments_tab.html.erb
<div class="tab-pane active" id="enrollments" role="tabpanel" aria-labelledby="enrollments-tab-tab">

  <div class="table-responsive">

    <% unless @training_session.instructors.include? current_user %>
    <div>
      <span class="glyphicon glyphicon-list-alt">
        <% if @user_enrollment.blank? %>
            <%= link_to 'Enroll', training_session_enrollments_path(@training_session, enrollment: {user_id: current_user, training_session_id: @training_session}), method: :post, class: 'btn btn-default' if !@training_session.full? %>
        <% else %>
            <%= link_to 'Un-enroll', training_session_enrollment_path(@training_session, @user_enrollment), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-default' %>
        <% end %>
      </span>
    </div>
    <% end %>

    <table class="table v-middle">
      <thead>
      <tr>
        <th>Attended</th>
        <th>User</th>
        <th>Created Date</th>
        <th class="text-center">Instructor Rating</th>
        <% if current_user.has_cached_role?(:admin) || current_user.has_cached_role?(:workshops_admin) %>
            <th>Actions</th>
        <% end %>
      </tr>
      </thead>
      <tbody id="responsive-table-body">
      <%= content_tag_for(:tr, @training_session.enrollments) do |enrollment| %>
          <td>
            <%= check_box_tag "attended-#{enrollment.id}", enrollment.id, enrollment.attended,
                              disabled: !(current_user.has_cached_role?(:admin) || current_user.has_cached_role?(:workshops_admin) || current_user.has_cached_role?(:instructor, @training_session)),
                              data: {
                                  remote: true,
                                  url: training_session_enrollment_path(@training_session, enrollment),
                                  method: :patch,
                                  'session-rating': enrollment.session_rating ? enrollment.session_rating.rating : 0,
                                  'own-enrollment': enrollment.user == current_user
                              },
            class: 'attend-check' %>

          </td>
          <td>
            <div>
              <% if enrollment.session_rating.nil? %>
                  <%= enrollment.user.full_name %></a>
                <% else %>
                <%= link_to session_rating_path(enrollment.session_rating.id) do %>
                    <%= enrollment.user.full_name %></a>
                <% end %>
              <% end %>
            </div>
            <div class="text-muted">
              <%= enrollment.user.email %>
            </div>
          </td>
          <td><%= enrollment.created_at.strftime('%B %d, %Y') %></td>
          <!-- Rating -->
          <td class="text-center">
            <% if enrollment.attended %>
              <%= session_rate enrollment&.session_rating&.rating ? enrollment.session_rating.rating : 0, clickable: enrollment.user == current_user && enrollment.attended %>
            <% end %>
          </td>
          <!-- un-enroll/ -->
          <% if current_user.has_cached_role?(:admin) || current_user.has_cached_role?(:workshops_admin) %>
              <td><%= link_to 'Un-enroll', training_session_enrollment_path(@training_session, enrollment), method: :delete, data: {confirm: 'Are you sure?'} %></td>
          <% end %>
      <% end %>
      </tbody>
    </table>

    <% if current_user.has_cached_role?(:admin) || current_user.has_cached_role?(:workshops_admin) %>
        <%= form_for Enrollment.new, url: training_session_enrollments_path(@training_session) do |f| %>
            <div class="form-group">

              <div class="col-sm-9">
                <%= f.autocomplete :user %>
                <%= f.hidden_field :training_session_id, value: @training_session.id %>
              </div>
              <%= f.submit value: 'Enroll User', class: 'btn btn-primary  col-sm-2' %>
            </div>
        <% end %>
    <% end %>
  </div>


</div>

app/views/training_sessions/_finance_tab.html.erb
<div class="tab-pane" id="finance" role="tabpanel" aria-labelledby="finance-tab-tab">
  <% if current_user.has_cached_role?(:financial_admin) || current_user.has_cached_role?(:admin) || current_user.has_cached_role?(:workshops_admin) %>
      <button class="btn btn-primary dropdown-toggle" type="button" id="generalLedgersDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Add a general ledger entry
      </button>
  <% end %>

  <!-- Dropdown menu for the general ledger entries -->
  <div class="dropdown-menu" aria-labelledby="generalLedgersDropdown">
    <a href="#" class="dropdown-item" data-toggle="modal" data-target="#glModal">Add a new entry</a>
    <%= link_to training_session_general_ledgers_link_path(@training_session), class: 'dropdown-item' do %>
        Link existing entry
    <% end %>
  </div>

  <div class="table-responsive">
    </br>
    <table class="table table-striped table-bordered table-hover">
      <tr>
        <th>Description</th>
        <th>Transaction date</th>
        <th>Amount</th>
        <th>Account</th>
        <th>Category</th>
        <th class="text-center">Actions</th>
      </tr>
      </thead>

      <tbody>
      <%= content_tag_for(:tr, @training_session.general_ledgers) do |general_ledger| %>
          <td>
            <div>
              <%= general_ledger.description %>
            </div>
            <div class="small text-muted">
              <strong>Transaction type: </strong><%= general_ledger.transaction_type %>
            </div>
          </td>
          <td><%= general_ledger.transaction_date.strftime('%B %d, %Y') %></td>
          <td><%= "#{general_ledger.amount_currency.format} #{general_ledger.amount_currency.currency}" %></td>
          <td><%= general_ledger.financial_account.name %></td>
          <td><%= general_ledger.ledger_category.name %></td>
          <td> <%= crud_links general_ledger %></td>
      <% end %>

      <tr>
        <td colspan="2"><strong>Total Planned</strong></td>
        <td>
          <strong><%= "#{@training_session.total_planned.format} #{@training_session.total_planned.currency}" %></strong>
        </td>
        <td></td>
        <td></td>
        <td></td>
      </tr>

      <tr>
        <td colspan="2"><strong>Total Debit</strong></td>
        <td><strong><%= "#{@training_session.total_debit.format} #{@training_session.total_debit.currency}" %></strong>
        </td>
        <td></td>
        <td></td>
        <td></td>
      </tr>

      <tr>
        <td colspan="2"><strong>Total Credit</strong></td>
        <td>
          <strong><%= "#{@training_session.total_credit.format} #{@training_session.total_credit.currency}" %></strong>
        </td>
        <td></td>
        <td></td>
        <td></td>
      </tr>

      </tbody>
    </table>
  </div>
</div>

app/views/training_sessions/_form.html.erb
<div class="panel panel-default">
  <div class="panel-body">

    <%= form_for(@training_session, html: {class: "form-horizontal", role: "form"}) do |f| %>
        <% if @training_session.errors.any? %>
            <div class="alert alert-danger alert-dismissable" role="alert">
              <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
              <h4><%= pluralize(@training_session.errors.count, "error") %> prohibited this training_session from being
                saved:</h4>

              <ul>
                <% @training_session.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

      <%= f.text_field :title, { label_classes: 'col-sm-12 required-field' } %>
      <%= f.text_area :description, { label_classes: 'col-sm-12 required-field' } %>

        <div class="row">
          <div class="col-md-6">
            <%= f.number_field :min_group_size %>
          </div>
          <div class="col-md-6">
            <%= f.number_field :max_group_size %>
          </div>
        </div>




        <div class="form-group">
          <div class="row">
            <div class="col-md-6">

              <%=f.datetimepicker :start_date, :value => "#{@training_session.start_date} #{@training_session.start_time}" %>


            </div>
          <div class="col-md-6">
                <%= f.text_field :url, class: "form-control" %>
          </div>
          </div>
        </div>
        <%= f.number_field :duration_in_minutes %>
        <div class="row">
          <div class="col-md-6">
            <%= f.number_field :compensation %>
          </div>
          <div class="col-md-6">
            <%= f.check_box :compensation_delivered %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :session_type, class: 'col-sm-12 control-label' %>
          <div class="col-sm-12">
            <%= f.select :training_session, :session_type, TRAINING_SESSION_TYPES, class: 'form-control' %>
          </div>
        </div>
        <%= f.autocomplete :class_location, { label_classes: 'col-sm-12 required-field' } %>
        <%= f.autocomplete :course %>
        <%= f.autocomplete :instructors %>


        <div class="form-group">
          <div class="col-sm-10">
            <%= f.submit class: 'btn btn-primary' %>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/training_sessions/_grading_tab.html.erb
<div class="tab-pane" id="grading" role="tabpanel" aria-labelledby="grading-tab-tab">
  <div class="tab-responsive">
    <% if current_user.has_cached_role?(:workshops_admin) || current_user.has_cached_role?(:training_admin) %>

      <p>
        you are an Admin
      </p>

      <p>
        <select>
          <option value="file">Examen en la pagina</option>
          <option value="test">Test de codigo</option>
          <option value="both">Why no both?</option>
        </select>
      </p>

      <input type="file" name="fileToUpload" id="fileToUpload">
      <input type="submit" value="Upload reference" name="submit">

  <% else current_user.has_cached_role?(:user) %>
      <p>
        you are a user
      </p>
      <!--<p>
        <form >
          <button type="submit">Download Template</button>
        </form>
      </p>

      <input type="file" name="fileToUpload" id="fileToUpload">
      <input type="submit" value="Upload file" name="submit">-->

      <%= form_tag({:action => 'grade_my_code', :controller => 'grading'}, :multipart => true) do %>
          <p><label for="upload_file">Select File</label>
          <%= file_field 'upload', 'datafile' %></p>
          <%= submit_tag "Upload file" %>
      <% end %>



    <% end %>
  </div>
</div>

app/views/training_sessions/edit.html.erb
<% title 'Editing training_session' %>

<div class="row">
  <div class="container-fluid">
    <div class="pull-right">
      <%= link_to training_sessions_path, class: 'btn btn-default' do %>
          <span class="glyphicon glyphicon-list-alt"></span>
          Back
      <% end %>
      <%= link_to @training_session, class: 'btn btn-primary' do %>
          <span class="glyphicon glyphicon-info-sign"></span>
          Show
      <% end %>
    </div>
  </div>
</div>


<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        Classes & Workshops
      </div>
      <div class="card-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/training_sessions/index.html.erb
<% title 'Classes & Workshops' %>

<div class="card">

  <div class="card-header">
    <h5><strong><%= yield(:title) %></strong></h5>
  </div>

  <div class="card-body">

    <div class="row">
      <div class="col-12">

            <div class="pull-left">
              <%= form_tag(training_sessions_path, method: :get) do %>

            <div class="form-group row">
              <div class="col-md-12">
                <div class="input-group">
                  <%= text_field_tag :q, params[:q], class: 'form-control' %>
                  <span class="input-group-btn">
                    <%= button_tag nil, name: nil, class: 'btn btn-primary' do %>
                      <i class="fa fa-search"></i> Search
                    <% end %>
                  </span>
                </div>
              </div>
            </div>

          <% end %>
        </div>

        <div class="pull-right">
          <% if current_user.has_cached_role?(:workshops_admin) || current_user.has_cached_role?(:admin) %>
              <%= link_to new_training_session_path, class: 'btn btn-primary' do %>
                  <span class="glyphicon glyphicon-plus"></span>
                  New Training session
              <% end %>
          <% end %>
        </div>
      </div>
    </div>

    <%= render 'training_sessions/training_session_table' %>

  </div>
</div>

app/views/training_sessions/new.html.erb
<% title 'New training_session' %>

<div class="row">
  <div class="container-fluid">
    <div class="pull-right">
      <%= link_to training_sessions_path, class: 'btn btn-default' do %>
          <span class="glyphicon glyphicon-list-alt"></span>
          Back
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <%=  yield(:title) %>
      </div>
      <div class="card-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/training_sessions/show.html.erb
<% if params[:load_ledger] %>
    <script>
      $(window).load(function () {
        $('#glModal').modal('show');
      });
    </script>
<% end %>
<% title 'Training Session' %>
<div class="row">
  <div class="container-fluid">
    <div class="pull-right">
      <%= link_to training_sessions_path, class: 'btn btn-default' do %>
        <span class="glyphicon glyphicon-list-alt"></span>
        Back
      <% end %>
      <% if current_user.has_cached_role?(:admin) || current_user.has_cached_role?(:workshops_admin) %>
        <%= link_to edit_training_session_path(@training_session), class: 'btn btn-primary' do %>
          <span class="glyphicon glyphicon-pencil"></span>
          Edit
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <div class="pull-left">
          <h5>Type: <strong><%= @training_session.session_type.capitalize %></strong></h5>
          <h4 class="text-headline"><%= @training_session.title %></h4>
        </div>
        <% if current_user.has_cached_role?(:admin) || current_user.has_cached_role?(:workshops_admin) %>
        <div class="admin-actions pull-right">
          <button id="print-button" class="btn btn-primary"> <i class="fa fa-print"></i> Print</button>
        </div>
        <% end %>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-md-8">
            <%= @training_session.description %>
          </div>
          <div class="col-md-3 col-md-offset-1">
            <p class="text-caption">
              <strong>
                <i class="fa fa-calendar fa-fw"></i> <%= @training_session.start_date %>
                <i class="fa fa-clock-o fa-fw"></i> <%= @training_session.start_time %>
                <br/>
                <i class="fa fa-hourglass-2 fa-fw"></i> <%= @training_session.duration_in_minutes %> min &nbsp;
                <br />
                <i class="fa fa-mortar-board fa-fw"></i> Min. group: <%= @training_session.min_group_size %>
                <br/>
                <i class="fa fa-mortar-board fa-fw"></i> Max. group: <%= @training_session.max_group_size %>
                <br/>
                <i class="fa fa-check fa-fw"></i> Attendance: <%= @training_session.attendance %>
                <br/>
                <i class="fa fa-book" aria-hidden="true"></i> Course: <%= @training_session.course.title if @training_session.course.present? %>
                <br/>
                <i class="fa fa-link" aria-hidden="true"></i> URL: <%= @training_session.url if @training_session.url.present? %>
                <br/>
                <i class="fa fa-usd" aria-hidden="true"></i> Compensation(USD): <%= @training_session.compensation %> &nbsp;
                Delivered:  <% if @training_session.compensation_delivered %>
                              <i class="fa fa-check" aria-hidden="true"></i>
                            <% else %>
                              <i class="fa fa-times" aria-hidden="true"></i>
                            <% end %>
              </strong>
            </p>
          </div>
        </div>

        <hr class="margin-none"/>

        <div class="row">
          <div class="col-md-8">
            <i class="fa fa-user fa-fw"></i> Instructors:
          </div>
          <div class="col-md-3 col-md-offset-1">
            <i class="fa fa-thumb-tack" aria-hidden="true"></i> Location:
          </div>
        </div>

        <div class="row">
          <div class="col-md-8">
            <%= content_tag_for(:span, @training_session.instructors, class: 'label bg-gray-dark') do |instructor| %>
              <%= instructor %>
            <% end %>
          </div>
          <div class="col-md-3 col-md-offset-1">
            <p>
              <strong><%= @training_session.class_location.name %></strong>, <%= @training_session.class_location.timezone %>
            </p>
          </div>
        </div>

        <hr>
        <div class="admin-actions pull-right">
          <% if @training_session.enrolled_and_attended_user?(current_user) %>
            <%= link_to training_sessions_path do %>
                  <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#ratingModal">
                    <span class="glyphicon glyphicon-list-alt fa fa-check"></span>
                    Rate Session
                  </a>
            <% end %>
          <% end %>
        </div>

        <ul class="nav nav-tabs" id="training_session_tabs" role="tablist">

          <li class="nav-item active">
            <a class="nav-link active" id="enrollments-tab" data-toggle="tab" href="#enrollments" role="tab" aria-controls="enrollments" aria-selected="true">
              <%= @training_session.full? ? 'Enrollments (Full)' : 'Enrollments' %>
            </a>
          </li>

          <%# if !@user_enrollment.blank? || current_user.has_cached_role?(:admin) || current_user.has_cached_role?(:workshops_admin) || current_user.has_cached_role?(:training_admin) %>
            <li class="nav-item">
              <a class="nav-link" id="grading-tab" data-toggle="tab" href="#grading" role="tab" aria-controls="grading" aria-selected="false">Grading</a>
            </li>
          <%# end %>

          <% if current_user.has_cached_role?(:financial_admin) || current_user.has_cached_role?(:admin) || current_user.has_cached_role?(:workshops_admin) %>
              <li class="nav-item">
                <a class="nav-link" id="finance-tab" data-toggle="tab" href="#finance" role="tab" aria-controls="finance" aria-selected="false">Finance</a>
              </li>
          <% end %>

        </ul>

        <div class="tab-content">
          
          <%= render 'enrollments_tab' %>

          <%= render 'grading_tab' %>

          <% if current_user.has_cached_role?(:financial_admin) || current_user.has_cached_role?(:admin) || current_user.has_cached_role?(:workshops_admin) %>
            <%= render 'finance_tab' %>
          <% end %>

        </div>

      </div>
    </div>
  </div>
</div>

<!-- Create general ledger entry modal -->
<div class="modal fade" id="glModal" tabindex="-1" role="dialog" aria-labelledby="glModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= render 'general_ledgers/form_modal' %>
    </div>
  </div>
</div>

<!-- Link an existing general ledger entry modal -->

<%= render 'session_ratings/form_modal' %>